---
abstract: 'Calculator plugin for Cobalt'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-Cobalt-Plugin-Calc
provides:
  Bot::Cobalt::Plugin::Calc:
    file: lib/Bot/Cobalt/Plugin/Calc.pm
    version: 0.001
  Bot::Cobalt::Plugin::Calc::Parser:
    file: lib/Bot/Cobalt/Plugin/Calc/Parser.pm
    version: 0
requires:
  Bot::Cobalt::Common: 0
  Bot::Cobalt::Core: 0
  Bot::Cobalt::Serializer: 0
  Parser::MGC: 0.10
  perl: v5.12.1
  strictures: 1
resources:
  license: http://dev.perl.org/licenses/
version: 0.001
